modLoader="javafml"
loaderVersion="[34,)"
license="GNU LGPLv3"
logoFile="logo.png"
issueTrackerURL="https://github.com/gdavid04/PsionicUtilities/issues"
displayURL="https://github.com/gdavid04/PsionicUtilities"
authors="GDavid"
[[mods]]
modId="psionicutilities"
version="${file.jarVersion}"
displayName="Psionic Utilities"
description='''
A Psi addon to make spell programming easier
'''
[[dependencies.psionicutilities]]
	modId="forge"
    mandatory=true
    versionRange="[43.3.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.psionicutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.psionicutilities]]
    modId="psi"
    mandatory=true
    versionRange="[1.19-101,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.psionicutilities]]
    modId="phi"
    mandatory=false
    versionRange="[1.16-2.5,)"
    ordering="AFTER"
    side="BOTH"
