modLoader="javafml"
loaderVersion="[34,)"
license="GNU LGPLv3"
logoFile="logo.png"
issueTrackerURL="https://github.com/gdavid04/PsionicUtilities/issues"
displayURL="https://github.com/gdavid04/PsionicUtilities"
authors="GDavid"
[[mods]]
modId="psionicutilities"
version="${file.jarVersion}"
displayName="Psionic Utilities"
description='''
A Psi addon to make spell programming easier
'''
[[dependencies.psionicutilities]]
	modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.psionicutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.psionicutilities]]
    modId="psi"
    mandatory=true
    versionRange="[1.16-95,)"
    ordering="AFTER"
    side="BOTH"
